### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by HydraGene** [ethanwharris/gnome-nvidia-extension#156]
# Expected Behavior

It should just load after installing from https://extensions.gnome.org/extension/1320/nvidia-gpu-stats-tool/ or Gnome Tweak Tool > Install Shell Extension.
I have met the requirements: nvidia-settings and nvidia-smi.

# Current Behavior

The extension won't load. Not even after restarting Gnome Shell. I receive no error messages whatsoever. In Gnome Tweak Tool I get warning triangle saying "Error loading extension".

## Steps to Reproduce

A:
1. Go to https://extensions.gnome.org/extension/1320/nvidia-gpu-stats-tool/ and load Gnome Shell Integration.
2. Click on ON|OFF button, and Install. 
3. Nothing happens, except ON|OFF button goes back to OFF.

B:
1. Go to https://extensions.gnome.org/extension/1320/nvidia-gpu-stats-tool/ and manual download 3.22 v5.
2. Open Gnome Tweak Tool and load the .zip file.
3. Nothing happens, except after reloading Gnome Shell the extension shows with warning triangle.

## Context

* Nvidia-Settings Version (if used): 390.48
* Nvidia-smi version (if used): 390.67
* Operating System: Debian 9 Stretch, Gnome Shell 3.22.2
* GPU: NVIDIA GeForce GTX 960M

**Comment by ethanwharris** [comment]
@HydraGene Thank you for raising an issue. Could you run `journalctl /usr/bin/gnome-shell -f` in a terminal and then restart gnome shell (`ALT + F2` then `r, ENTER`). Doing this should give you some log output, could you then paste the output here?

**Comment by HydraGene** [comment]
Thank you for your reply.

This is the output I got.
```
user0@PE60-2QE:~$ sudo journalctl /usr/bin/gnome-shell -f
[sudo] password for user0: 
-- Logs begin at Fri 2018-07-27 17:43:14 CEST. --
aug 01 16:48:26 PE60-2QE gnome-shell[1315]: JS LOG: System monitor applet disable
aug 01 16:48:29 PE60-2QE gnome-shell[1315]: JS LOG: System monitor applet enabling
aug 01 16:48:29 PE60-2QE gnome-shell[1315]: JS LOG: System monitor applet enabling done
aug 01 16:48:29 PE60-2QE gnome-shell[1315]: JS LOG: Could not find NVIDIA GPU model name, using general fallback.
aug 01 17:34:35 PE60-2QE gnome-shell[1315]: Source ID 1472925 was not found when attempting to remove it
aug 01 17:34:35 PE60-2QE gnome-shell[1315]: JS LOG: System monitor applet disable
aug 01 17:58:09 PE60-2QE gnome-shell[1315]: JS LOG: System monitor applet enabling
aug 01 17:58:09 PE60-2QE gnome-shell[1315]: JS LOG: System monitor applet enabling done
aug 01 17:58:09 PE60-2QE gnome-shell[1315]: JS LOG: Could not find NVIDIA GPU model name, using general fallback.
aug 01 17:58:15 PE60-2QE org.gnome.Shell.desktop[1315]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x160010b (Guake!)
```
The above was before the gnome shell restart, and the below was added after the gnome shell restart.
```
aug 01 18:02:15 PE60-2QE org.gnome.Shell.desktop[1315]: Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
aug 01 18:02:16 PE60-2QE gnome-shell[1315]: JS LOG: Failed to launch ibus-daemon: Failed to execute child process "ibus-daemon" (No such file or directory)
aug 01 18:02:16 PE60-2QE gnome-shell[1315]: JS WARNING: [/home/user0/.local/share/gnome-shell/extensions/nvidiautil@ethanwharris/spawn.js 21]: function spawnAsync does not always return a value
aug 01 18:02:16 PE60-2QE gnome-shell[1315]: JS ERROR: Exception in callback for signal: extension-found: SyntaxError: missing : after property id @ /home/user0/.local/share/gnome-shell/extensions/nvidiautil@ethanwharris/settingsProvider.js:29
aug 01 18:02:16 PE60-2QE gnome-shell[1315]: JS LOG: Could not find NVIDIA GPU model name, using general fallback.
aug 01 18:02:16 PE60-2QE gnome-shell[1315]: JS LOG: System monitor applet init from /home/user0/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com
aug 01 18:02:16 PE60-2QE gnome-shell[1315]: JS LOG: System monitor applet enabling
aug 01 18:02:16 PE60-2QE gnome-shell[1315]: JS LOG: System monitor applet enabling done
aug 01 18:02:18 PE60-2QE gnome-shell[1315]: GNOME Shell started at Wed Aug 01 2018 18:02:16 GMT+0200 (CEST)
```

What can I do next?

**Comment by ethanwharris** [comment]
@HydraGene Thanks for providing the output. The error seems to be relating to the syntax of our function definitions. I've made an attempt at fixing this in the branch fix/syntax. Could you checkout that branch:

`git pull`
`git checkout fix/syntax`

And then re-install the extension:

`make install`

If that works please let us know :)

**Comment by HydraGene** [comment]
BTW, I forgot to mention that I use Bumblebee and that I had "Optimus with Bumblebee (beta)" activated, in case that has any influence on this issue.

It seems to not have worked.. 
I have cloned the repository, went in the folder, and then followed your instructions.
I tried once to re-install and once to remove and then install. Both no result.

Output of restart gnome shell:
```
aug 05 14:13:09 PE60-2QE org.gnome.Shell.desktop[2078]: Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
aug 05 14:13:10 PE60-2QE gnome-shell[2078]: JS LOG: Failed to launch ibus-daemon: Failed to execute child process "ibus-daemon" (No such file or directory)
aug 05 14:13:10 PE60-2QE gnome-shell[2078]: JS WARNING: [/home/user0/.local/share/gnome-shell/extensions/nvidiautil@ethanwharris/spawn.js 21]: function spawnAsync does not always return a value
aug 05 14:13:10 PE60-2QE gnome-shell[2078]: JS WARNING: [/home/user0/.local/share/gnome-shell/extensions/nvidiautil@ethanwharris/formatter.js 87]: anonymous function does not always return a value
aug 05 14:13:11 PE60-2QE gnome-shell[2078]: JS LOG: Extension "nvidiautil@ethanwharris" had error: ReferenceError: Processor is not defined
aug 05 14:13:11 PE60-2QE gnome-shell[2078]: JS LOG: System monitor applet init from /home/user0/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com
aug 05 14:13:11 PE60-2QE gnome-shell[2078]: JS LOG: System monitor applet enabling
aug 05 14:13:11 PE60-2QE gnome-shell[2078]: JS LOG: System monitor applet enabling done
aug 05 14:13:12 PE60-2QE gnome-shell[2078]: GNOME Shell started at Sun Aug 05 2018 14:13:10 GMT+0200 (CEST)
```
---
I noticed that when I change the settings of the extension from "Optimus with Bumblebee (beta)" to "Nvidia Settings and SMI" and restart shell, I get the following different output and error:
```
aug 05 14:20:11 PE60-2QE org.gnome.Shell.desktop[2078]: Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
aug 05 14:20:12 PE60-2QE gnome-shell[2078]: JS LOG: Failed to launch ibus-daemon: Failed to execute child process "ibus-daemon" (No such file or directory)
aug 05 14:20:12 PE60-2QE gnome-shell[2078]: JS WARNING: [/home/user0/.local/share/gnome-shell/extensions/nvidiautil@ethanwharris/spawn.js 21]: function spawnAsync does not always return a value
aug 05 14:20:12 PE60-2QE gnome-shell[2078]: JS WARNING: [/home/user0/.local/share/gnome-shell/extensions/nvidiautil@ethanwharris/formatter.js 87]: anonymous function does not always return a value
aug 05 14:20:12 PE60-2QE gnome-shell[2078]: JS LOG: error: Error parsing nvidia-settings: lines[i] is undefined
aug 05 14:20:12 PE60-2QE gnome-shell[2078]: JS LOG: Could not find NVIDIA GPU model name, using general fallback.
aug 05 14:20:12 PE60-2QE gnome-shell[2078]: JS LOG: System monitor applet init from /home/user0/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com
aug 05 14:20:12 PE60-2QE gnome-shell[2078]: JS LOG: System monitor applet enabling
aug 05 14:20:12 PE60-2QE gnome-shell[2078]: JS LOG: System monitor applet enabling done
aug 05 14:20:14 PE60-2QE gnome-shell[2078]: GNOME Shell started at Sun Aug 05 2018 14:20:12 GMT+0200 (CEST)
```
After I switched the settings, I could move the ON/OFF button. It seems to be activated. After I started an `optirun` job, I get the following error:
```
aug 05 14:33:29 PE60-2QE gnome-shell[2078]: JS LOG: error: Error parsing nvidia-smi: values[(intermediate value)] is undefined
```
Instruct me on the next steps we could take :)

**Comment by ethanwharris** [comment]
@HydraGene Thanks for your help. Ive made a change that should hopefully fix it. Could you checkout that branch again:

`git checkout fix/syntax`
`git pull`

And then re-install the extension and restart gnome shell:

`make install`

**Comment by ethanwharris** [comment]
Glad some of it is fixed! The bumblebee thing may be an easy fix, had to guess the commands. Could you run this and post the output please?

`optirun nvidia-settings -q GpuUUID -t`

**Comment by HydraGene** [comment]
Error, error and error.. Seems like I have one big error machine :p 
I have no idea what these mean. Sounds like something missing at the communication between the display and the gpu.
```

ERROR: Error querying enabled displays on GPU 0 (Missing Extension).

ERROR: Error querying connected displays on GPU 0 (Missing Extension).

ERROR: Error resolving target specification '' (No targets match target
       specification), specified in query 'GpuUUID'.

```

**Comment by ethanwharris** [comment]
Seems to be an error with the extension trying to query nvidia-settings. Ive made a branch which uses smi instead. Could you checkout fix/bumblebee and give it another go with the 'Optimuis with Bumblebee' provider:

`git pull`
`git checkout fix/bumblebee`

Thanks!

**Comment by HydraGene** [comment]
Still the same behavior.. Error loading extension.
The logs below:
```
-- Logs begin at Tue 2018-08-07 12:44:05 CEST. --
aug 07 14:01:53 PE60-2QE gnome-shell[1359]: JS WARNING: [/home/user0/.local/share/gnome-shell/extensions/nvidiautil@ethanwharris/formatter.js 87]: anonymous function does not always return a value
aug 07 14:01:54 PE60-2QE gnome-shell[1359]: JS LOG: Extension "nvidiautil@ethanwharris" had error: TypeError: this.providerProperties is undefined
aug 07 14:01:54 PE60-2QE gnome-shell[1359]: JS LOG: System monitor applet init from /home/user0/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com
aug 07 14:01:54 PE60-2QE gnome-shell[1359]: JS LOG: System monitor applet enabling
aug 07 14:01:54 PE60-2QE gnome-shell[1359]: JS LOG: System monitor applet enabling done
aug 07 14:01:55 PE60-2QE gnome-shell[1359]: GNOME Shell started at Tue Aug 07 2018 14:01:53 GMT+0200 (CEST)
aug 07 14:28:51 PE60-2QE gnome-shell[1359]: JS LOG: System monitor applet disable
aug 07 14:28:53 PE60-2QE gnome-shell[1359]: JS LOG: System monitor applet enabling
aug 07 14:28:53 PE60-2QE gnome-shell[1359]: JS LOG: System monitor applet enabling done
aug 07 14:28:53 PE60-2QE gnome-shell[1359]: JS LOG: Could not find NVIDIA GPU model name, using general fallback.

```
After this, I tried `optirun nvidia-settings` without the options you specified, and I got this:
```
aug 07 14:33:57 PE60-2QE org.gnome.Shell.desktop[1359]: primus: fatal: failed to load any of the libraries: /usr/lib/x86_64-linux-gnu/nvidia/libGL.so.1:/usr/lib/i386-linux-gnu/nvidia/libGL.so.1:/usr/lib/nvidia/libGL.so.1
aug 07 14:33:57 PE60-2QE org.gnome.Shell.desktop[1359]: /usr/lib/x86_64-linux-gnu/nvidia/libGL.so.1: cannot open shared object file: No such file or directory
aug 07 14:33:57 PE60-2QE org.gnome.Shell.desktop[1359]: /usr/lib/i386-linux-gnu/nvidia/libGL.so.1: cannot open shared object file: No such file or directory
aug 07 14:33:57 PE60-2QE org.gnome.Shell.desktop[1359]: /usr/lib/nvidia/libGL.so.1: cannot open shared object file: No such file or directory
aug 07 14:34:02 PE60-2QE org.gnome.Shell.desktop[1359]: primus: fatal: failed to load any of the libraries: /usr/lib/x86_64-linux-gnu/nvidia/libGL.so.1:/usr/lib/i386-linux-gnu/nvidia/libGL.so.1:/usr/lib/nvidia/libGL.so.1
aug 07 14:34:02 PE60-2QE org.gnome.Shell.desktop[1359]: /usr/lib/x86_64-linux-gnu/nvidia/libGL.so.1: cannot open shared object file: No such file or directory
aug 07 14:34:02 PE60-2QE org.gnome.Shell.desktop[1359]: /usr/lib/i386-linux-gnu/nvidia/libGL.so.1: cannot open shared object file: No such file or directory
aug 07 14:34:02 PE60-2QE org.gnome.Shell.desktop[1359]: /usr/lib/nvidia/libGL.so.1: cannot open shared object file: No such file or directory

```
---
I also ran `optirun nvidia-settings -V` of which the output is:
```
user0@PE60-2QE:~$ optirun nvidia-settings -V

WARNING: NV-CONTROL extension not found on this Display.


ERROR: Error querying enabled displays on GPU 0 (Missing Extension).


ERROR: Error querying connected displays on GPU 0 (Missing Extension).


WARNING: NV-CONTROL extension not found on this Display.


WARNING: Unable to determine number of NVIDIA GPUs on ':1'.


WARNING: Unable to determine number of NVIDIA Frame Lock Devices on ':1'.


WARNING: Unable to determine number of NVIDIA VCSs on ':1'.


WARNING: Unable to determine number of NVIDIA SDI Input Devices on ':1'.


WARNING: Unable to determine number of NVIDIA Fans on ':1'.


WARNING: Unable to determine number of NVIDIA Thermal Sensors on ':1'.


WARNING: Unable to determine number of NVIDIA 3D Vision Pro Transceivers on
         ':1'.


WARNING: Unable to determine number of NVIDIA Display Devices on ':1'.


WARNING: Unable to determine number of NVIDIA X Screens on ':1'.

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.


```
Then nvidia-settings runs, and I get a window with the following message: "You do not appear to be using NVIDIA X driver. Please edit your X configuration file (just run 'nvidia-xconfig' as root), and restart the X server."
However the Debian Wiki Bumblebee page says that I shouldn't.

**Comment by ethanwharris** [comment]
Ok, that error was caused by a minor bug. Hopefully this should fix it. Seems like nvidia-settings doesn't really work with bumblebee because it needs an x server setup. So I've switched the bumblebee provider to use nvidia-smi instead. Could you try that branch again:

`git checkout fix/bumblebee`
`git pull`

If that doesn't work. Could you post the output of the following command?

`optirun nvidia-smi --query-gpu=gpu_name --format=csv,noheader`

Thanks!

**Comment by HydraGene** [comment]
Making some progress. 
With the Optimus with Bumblebee setting it is at least activated. I can switch ON/OFF and I see it in the top bar. But it doesn't show the correct data yet. Memory/Fan/Power shows static 0, Utilization shows static 6852004% without optirun, static 100658172004% with optirun.
Optimus with Bumblebee setting shows "GPU 0" while the Nvidia SMI setting shows "0: GeForce GTX 960M"

Output of `optirun nvidia-smi --query-gpu=gpu_name --format=csv,noheader`:
```
GeForce GTX 960M
```

**Comment by ethanwharris** [comment]
Ooops, the commands seem to be working but the parsing of output was wrong. Ive updated the branch to fix that. If you could pull fix/bumblebee and make install one more time that should hopefully work!

**Comment by ethanwharris** [comment]
Actually, don't try just yet, I seem to be getting an error

**Comment by ethanwharris** [comment]
@HydraGene Ok, sorry about that. The extension should now, hopefully, be working!

**Comment by HydraGene** [comment]
Now it's working like a charm! Thanks a lot!
No errors, responsive when running and quitting optirun and the right data is shown.

One small issue still: The extension shows a gear button which should take me to Nvidia Settings. But Nvidia Settings does not show. `journalctl /usr/bin/gnome-shell -f` gives me:
```
aug 07 16:30:56 PE60-2QE org.gnome.Shell.desktop[1359]: primus: fatal: failed to load any of the libraries: /usr/lib/x86_64-linux-gnu/nvidia/libGL.so.1:/usr/lib/i386-linux-gnu/nvidia/libGL.so.1:/usr/lib/nvidia/libGL.so.1
aug 07 16:30:56 PE60-2QE org.gnome.Shell.desktop[1359]: /usr/lib/x86_64-linux-gnu/nvidia/libGL.so.1: cannot open shared object file: No such file or directory
aug 07 16:30:56 PE60-2QE org.gnome.Shell.desktop[1359]: /usr/lib/i386-linux-gnu/nvidia/libGL.so.1: cannot open shared object file: No such file or directory
aug 07 16:30:56 PE60-2QE org.gnome.Shell.desktop[1359]: /usr/lib/nvidia/libGL.so.1: cannot open shared object file: No such file or directory

```
I think if you can make the gear button run `optirun -b none nvidia-settings -c :8`, then Nvidia Settings should show without problems. I got this command from the [Bumblebee FAQ](https://github.com/Bumblebee-Project/Bumblebee/wiki/FAQ#nvidia-settings-doesnt-work-it-tells-me-im-not-using-the-card) and it works fine when I run this command in the terminal. 
Can you take a quick look at this?

Otherwise consider this issue fixed. Thanks again!

**Comment by ethanwharris** [comment]
Glad it's finally working! I've switched the settings command for the one you gave. Hopefully that should work now. Same branch :)

**Comment by HydraGene** [comment]
Perfect! It works!
Thanks a lot :)
